apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Endpoint
    server: https://acme-v02.api.letsencrypt.org/directory

    email: walaxazevedo728@gmail.com

    # Chave privada
    privateKeySecretRef:
      name: letsencrypt-prod

    # Configuração do solver HTTP-01
    solvers:
    - http01:
        ingress:
          class: nginx
