apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami-sa
  namespace: devops-challenge
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-challenge
  name: whoami-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: whoami-rolebinding
  namespace: devops-challenge
subjects:
- kind: ServiceAccount
  name: whoami-sa
  namespace: devops-challenge
roleRef:
  kind: Role
  name: whoami-role
  apiGroup: rbac.authorization.k8s.io
